version: '3.8'
services:
  quixi:
    build:
      context: ..
      dockerfile: docker/Dockerfile.quixi
    ports:
      - "8001:8001"
    volumes:
      - ..:/src:cached

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"

  chatbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.chatbot
    depends_on:
      - quixi
      - mqtt
