FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish QuIXI/QuIXI.sln -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8001
ENTRYPOINT ["dotnet", "QuIXI.dll", "--config", "ixian.cfg", "--apiport", "8001"]
